version: 2.1
jobs:
  phpunit:
    docker:
      - image: circleci/php:8.2

    working_directory: /app

    steps:
      - checkout

      # Install dependencies using Composer
      - run:
          name: Install Dependencies
          command: composer install

      # Run PHPUnit tests
      - run:
          name: Run PHPUnit tests
          command: vendor/bin/phpunit

  lint:
    docker:
      - image: circleci/php:7.4

    working_directory: /app

    steps:
      - checkout

      # Install dependencies using Composer
      - run:
          name: Install Dependencies
          command: composer install

      # Run PHP linting (you can use a linter like PHP_CodeSniffer)
      - run:
          name: Run PHP lint
          command: vendor/bin/phpcs --standard=PSR2 src/

workflows:
  version: 2
  build:
    jobs:
      - phpunit
      - lint
